### ISSUE TITLE
cifar training is throwing an error.

### ISSUE THREAD

**Issue by musafirsafwan** [openai/improved-gan#2]
Hi, I am getting this error when I run cifar_feature_matching or cifar_minibatch_discrimination but not when I run mnist. Please help.

```
Traceback (most recent call last):
  File "train_cifar_feature_matching.py", line 51, in <module>
    gen_dat = ll.get_output(gen_layers[-1])
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/bmi/Downloads/improved-gan-master/mnist_svhn_cifar10/nn.py", line 120, in get_output_for
    op = T.nnet.abstract_conv.AbstractConv2d_gradInputs(imshp=self.target_shape, kshp=self.W_shape, subsample=self.stride, border_mode='half')
AttributeError: 'module' object has no attribute 'abstract_conv'
```

**Comment by musafirsafwan** [comment]
Updating theano to the latest version solved the issue.
