### ISSUE TITLE
question of implementation of inception score

### ISSUE THREAD

**Issue by youkaichao** [openai/improved-gan#39]
these lines puzzle me:

    w = sess.graph.get_operation_by_name("softmax/logits/MatMul").inputs[1]

    logits = tf.matmul(tf.squeeze(pool3, [1, 2]), w)

    softmax = tf.nn.softmax(logits)

I'm wondering, why not just use ``sess.graph.get_tensor_by_name('softmax:0')`` ? Why bother to manually   do the matrix multiplication and apply softmax? also, why not add the bias term?

**Comment by youkaichao** [comment]
ok , I know that inception model require the batch size to be 1 if we just run ``sess.graph.get_tensor_by_name('softmax:0')``. (the restriction comes from ``tf.get_default_graph().get_tensor_by_name('pool_3/_reshape/shape_1:0')`` which has the fixed value of ``[1, 2048]``. but still, I can't understand why not add the bias term

**Comment by youkaichao** [comment]
without the bias term ( as in the repo), I get 10.954855 +- 0.4320521 inception score on CIFAR-10(using test images). 

with the bias term ( as in the repo), I get 11.228305 +- 0.45700935 inception score on CIFAR-10(using test images). 

so I think that the bias term should be added. It matters.

**Comment by ZhimingZhou** [comment]
I also found this issue. I actually tested the inception score with bias
term and without inception score with a set of experiments: the basic
founding is that inception score with bias term is consistently higher than
the one without bias term, with a relatively fixed gap (or fixed ratio? I
don't remember the details).

It does matter a lot, but the official implementation does not take it into
account, so maybe most other reported inception scores also do not. I
choose to report the score without the bias term to provide a fair
comparison.

I think it is indeed important to know whether there has consideration
on keep or drop the bias term from the original author.

--
Zhiming Zhou

**Comment by youkaichao** [comment]
@ZhimingZhou @TimSalimans  maybe the author just forgot the bias term?

**Comment by youkaichao** [comment]
@Adherer  I think you can take a look at [here](https://easydl.readthedocs.io/en/latest/modules/easydl.tf.html?highlight=inception_score#easydl.tf.evaluation.get_inception_score). But it seems that the model file of that link has changed. Fortunately, I have saved a copy of that model file at [here](https://drive.google.com/open?id=1fmfrIGnSwDSs3tvXjS-jqYeswwiZWLuA). (It annoys me that the link still works but actually points to another model file)

**Comment by Adherer** [comment]
> @Adherer I think you can take a look at [here](https://easydl.readthedocs.io/en/latest/modules/easydl.tf.html?highlight=inception_score#easydl.tf.evaluation.get_inception_score). But it seems that the model file of that link has changed. Fortunately, I have saved a copy of that model file at [here](https://drive.google.com/open?id=1fmfrIGnSwDSs3tvXjS-jqYeswwiZWLuA). (It annoys me that the link still works but actually points to another model file)

I use your method,and get the code from that website.But it still did not work,and get this error:
Traceback (most recent call last):
  File "inception_score.py", line 156, in <module>
    score, std = get_inception_score(test_X, 'classify_image_graph_def.pb', batch_size=64, splits=10)
  File "inception_score.py", line 78, in get_inception_score
    w = sess.graph.get_tensor_by_name('softmax/weights_1:0')
  File "/home/liujian/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3207, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/liujian/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/liujian/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3077, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'softmax/weights_1:0' refers to a Tensor which does not exist. The operation, 'softmax/weights_1', does not exist in the graph."
